ALTER TABLE video_jobs
    ADD COLUMN started_at TIMESTAMPTZ,
    ADD COLUMN finished_at TIMESTAMPTZ,
    ADD COLUMN ffmpeg_ms BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN zip_bytes BIGINT NOT NULL DEFAULT 0;
